### ISSUE TITLE
Missing dependancy after debian upgrade

### ISSUE THREAD

**Issue by Wilkins** [ldidry/etherpad-admin#16]
Hi Luc,

I recently updated my debian from squeeze to wheezy, and my etherpad-admin service won't start anymore.
The etherpad itself works fine.
When I tried to start the service via `service etherpad-admin restart` I had the following error : 

`Restarting Etherpad-admin
Couldn't load application from file "/home/web/padadmin/script/etherpad_admin": Can't locate Etherpad/API.pm in @INC (@INC contains: ...... ) at /home/web/padadmin/script/../lib/EtherpadAdmin.pm line 4.
BEGIN failed--compilation aborted at /home/web/padadmin/script/../lib/EtherpadAdmin.pm line 4.
Compilation failed in require at (eval 96) line 1.
`

So I reinstalled : `cpan install Etherpad::API`.

Then the message was : 
`service etherpad-admin restart`
`Restarting Etherpad-admin
Couldn't load application from file "/home/web/padadmin/script/etherpad_admin": Can't locate object method "moniker" via package "EtherpadAdmin" at /home/web/padadmin/script/../lib/Mojolicious/Plugin/Template.pm line 10`

I read a little bit the README file of the github repository and found out about `Carton` (which wasn't needed before as far as I know), so I installed Carton via debian packages, and ran `carton install` in my /home/web/padadmin/ directory but I had the following error : `Can't locate cpanfile: (cpanfile)`

I don't know where to run the carton command.

Do I have to upgrade to a more recent version of etherpad-admin ?

Thank you.

**Comment by ldidry** [comment]
oO I missed that issue. Sorry guys.

You can remove the local folder in your etherpad-admin and redo `carton install`, it will do the job.

Explanation: when you first installed your cpan modules with `carton install`, it installed some of them in a `perl-5.18` folder somewhere in `local`. Now you have Perl 5.20, so it will not search for packages in `perl-5.18` folder bu in `perl-5.20`.

@julpec => this is your bug.

@Wilkins => I think this is the same problem, but I'm not sure. Please, give it a try and tell me if it's ok.

**Comment by julpec** [comment]
Thanks Luc, it's perfect !

**Comment by ldidry** [comment]
@Wilkins Sorry, I didn't read your message well. I recommend you to upgrade to the latest version of EtherpadAdmin and then use `carton install`. Don't forget to check if the init script needs to be upgraded (and the `/etc/default/etherpad-admin` file as well).

**Comment by Wilkins** [comment]
Hi Luc,

Here is what I've done :
```
$ cd INSTALL_DIR
$ git pull
# The following part is from the "Run it" par of the README
$ sudo cp examples/etherpad-admin.initscript /etc/init.d/etherpad-admin
$ sudo cp examples/etherpad-admin.default /etc/default/etherpad-admin
$ sudo vi /etc/default/etherpad-admin
```
In the `/etc/default/etherpad-admin` file, I put my vhost directory (ie `INSTALL_DIR`)

```
$ sudo update-rc.d etherpad-admin defaults
$ sudo service etherpad-admin start
Starting Etherpad-admin
Can't find cpanfile.snapshot: Run `carton install` to build the snapshot file.
 [ok]
```
So in the `INSTALL_DIR`, I ran : 
```
$ carton install
Installing modules using INSTALL_DIR/cpanfile
(Then it hung for long minutes, so I stopped it)
```
I checked the `local` folder but it's empty.

```
$ strace carton install 
[...]
close(4)                                = 0
stat("/etc/perl/App/cpanminus/fatscript", 0xc2d138) = -1 ENOENT (No such file or directory)
stat("/etc/perl/App/cpanminus/fatscript.pm", 0xc2d138) = -1 ENOENT (No such file or directory)
stat("/usr/local/lib/perl/5.14.2/App/cpanminus/fatscript", 0xc2d138) = -1 ENOENT (No such file or directory)
stat("/usr/local/lib/perl/5.14.2/App/cpanminus/fatscript.pm", 0xc2d138) = -1 ENOENT (No such file or directory)
stat("/usr/local/share/perl/5.14.2/App/cpanminus/fatscript", 0xc2d138) = -1 ENOENT (No such file or directory)
stat("/usr/local/share/perl/5.14.2/App/cpanminus/fatscript.pm", {st_mode=S_IFREG|0444, st_size=683001, ...}) = 0
lseek(3, 190, SEEK_SET)                 = 190
lseek(3, 0, SEEK_CUR)                   = 190
pipe([4, 5])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f027543c9d0) = 27349
close(5)                                = 0
rt_sigaction(SIGINT, {SIG_IGN, [], SA_RESTORER, 0x7f027482b030}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGQUIT, {SIG_IGN, [], SA_RESTORER, 0x7f027482b030}, {SIG_DFL, [], 0}, 8) = 0
wait4(27349, 
// hangs here.
```
After a while I got the following error message : 
```
Failed to fetch distribution DateTime-1.18
```
So I guessed it's was timeout problem.
So I launched again the `carton install` command and let it run forever (like 30min), and I got this : 
```
$ carton install
Installing modules using INSTALL_DIR/cpanfile
Successfully installed Try-Tiny-0.22
Successfully installed Module-Runtime-0.014
Successfully installed Module-Implementation-0.09
Successfully installed Params-Validate-1.17
Successfully installed ExtUtils-MakeMaker-7.04 (upgraded from 6.57_05)
Successfully installed Exporter-Tiny-0.042
Successfully installed List-MoreUtils-0.402
Successfully installed DateTime-Locale-0.45
Successfully installed Scalar-List-Utils-1.41 (upgraded from 1.23)
Successfully installed List-AllUtils-0.09
Successfully installed Class-Singleton-1.5
Successfully installed DateTime-TimeZone-1.84
Successfully installed DateTime-1.18
13 distributions installed
Complete! Modules were installed into INSTALL_DIR/local
```
Now everything works fine, and you can close this issue.
Hope this will help someone.

Thanks again for your support.

**Comment by ldidry** [comment]
Thx !

**Comment by JohnMcLear** [comment]
Good job on this bug report @Wilkins -- nice to see a good verbose bug report once in a while ;)

**Comment by Wilkins** [comment]
Oh well, it's just normal to do my job as a free software user.
I don't dev a lot, so I can at least report issues, and detail what I do :-)
